### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by t3rmix** [dockette/rendertron#46]
Hi,
i run into issue running latest Docker image on Docker version 20.10.6

`> rendertron@2.0.1 start /srv
node build/rendertron.js

Uncaught exception
Error: Failed to launch chrome!
/srv/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/srv/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.<anonymous> (/srv/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rendertron@2.0.1 start: `node build/rendertron.js`
npm ERR! Exit status 1
`
Any idea? thanks

**Comment by f3l1x** [comment]
Related https://github.com/dockette/rendertron/pull/16

I cannot build this image in Docker Hub. :(

**Comment by f3l1x** [comment]
I will switch to manul build today. I will let you know.

**Comment by t3rmix** [comment]
Wow, so fast. Thanks!

**Comment by f3l1x** [comment]
Solved https://hub.docker.com/repository/registry-1.docker.io/dockette/rendertron/tags?page=1&ordering=last_updated
